import { chromium } from 'playwright';
import assert from 'node:assert/strict';

const browser = await chromium.launch({ channel: 'chrome', headless: true });
const base = process.env.ZOOM_TEST_URL || 'http://localhost:5173';
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  let stored = { content: '', version: 0, updatedAt: null };
  let fail = false;
  const session = { id: 'test-session', projectId: 'test-project', round: 1, project: { title: 'Record test project' } };
  const snapshot = () => ({ session, note: stored, transcript: { status: 'unavailable', code: 'RTMS_NOT_CONNECTED' } });
  await context.route('**/api/meetings/host/status', route => route.fulfill({ json: { connected: false } }));
  await context.route('**/api/meeting-record-projects', route => route.fulfill({ json: [{ id: session.projectId, title: session.project.title }] }));
  await context.route('**/api/projects/test-project/interview-sessions', route => route.fulfill({ json: snapshot() }));
  await context.route('**/api/interview-sessions/test-session/record', route => route.fulfill({ json: snapshot() }));
  await context.route('**/api/interview-sessions/test-session/record/notes/me', async route => {
    assert.equal(route.request().headers()['x-hireos-record'], '1');
    if (fail) return route.fulfill({ status: 503, json: { code: 'TEST_UNAVAILABLE' } });
    const input = route.request().postDataJSON();
    if (input.version !== stored.version) return route.fulfill({ status: 409, json: { code: 'NOTE_VERSION_CONFLICT' } });
    stored = { content: input.content, version: stored.version + 1, updatedAt: new Date().toISOString() };
    return route.fulfill({ json: stored });
  });
  const page = await context.newPage(); const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('dialog', d => d.accept());
  await page.goto(`${base}/project/live`);
  await page.getByRole('combobox', { name: /Record project|记录项目/ }).selectOption('test-project');
  await page.getByRole('button', { name: /Open record|打开记录/ }).click();
  await page.waitForURL('**/*recordSession=test-session');
  const notes = () => page.getByRole('textbox', { name: /Meeting notes|会议笔记/ });
  await notes().fill('First interview note');
  await page.getByRole('status').filter({ hasText: /^(Saved|已保存)$/ }).waitFor();
  assert.equal(stored.content, 'First interview note');
  await page.reload(); assert.equal(await notes().inputValue(), 'First interview note');
  await page.getByRole('tab', { name: /Transcript|转写/ }).click();
  await page.getByText(/RTMS setup is required|需要先开通 Zoom RTMS/).waitFor();
  await page.getByRole('tab', { name: /Notes|笔记/ }).click();
  assert.equal(await notes().inputValue(), 'First interview note');
  fail = true; await notes().fill('Unsaved draft');
  await page.getByText('TEST_UNAVAILABLE').waitFor();
  assert.equal(await notes().inputValue(), 'Unsaved draft');
  fail = false; await page.locator('.meeting-record').getByRole('button', { name: /Retry|重试/ }).click();
  await page.getByRole('status').filter({ hasText: /^(Saved|已保存)$/ }).waitFor();
  stored = { content: 'Other tab note', version: stored.version + 1, updatedAt: new Date().toISOString() };
  await notes().fill('Local conflicting note');
  await page.getByRole('button', { name: /Compare server version|比较服务器版本/ }).click();
  await page.getByRole('button', { name: /Keep and save my draft|保留当前草稿并保存/ }).click();
  await page.getByRole('status').filter({ hasText: /^(Saved|已保存)$/ }).waitFor();
  assert.equal(stored.content, 'Local conflicting note');
  await page.getByRole('button', { name: /^(EN \/ 中|中 \/ EN)$/ }).click();
  assert.equal(await notes().inputValue(), 'Local conflicting note');
  await page.screenshot({ path: '/tmp/hireos-meeting-notes.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  const panel = await page.locator('.meeting-record').boundingBox();
  assert.ok(panel.width <= 390 && panel.x >= 0, 'record panel fits mobile viewport');
  const field = await notes().boundingBox();
  assert.ok(field.width <= panel.width, 'note editor fits panel');
  await page.screenshot({ path: '/tmp/hireos-meeting-notes-mobile.png', fullPage: true });
  assert.deepEqual(errors, []);
  console.log('PASS: autosave, refresh, tab and language switches, failure retry, explicit conflict resolution, RTMS unavailable');
} finally { await browser.close(); }
